#spring.h2.console.enabled=true
### default path: h2-console
#spring.h2.console.path=/h2-console
# 
#spring.datasource.url=jdbc:h2:file:./imsDB
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=root
# 
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#
## H2 database configuration
#spring.h2.console.enabled=true
# 
## JPA configurations
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
# 
 
 # Enable MySQL Database
spring.datasource.url=jdbc:mysql://mysql-db:3306/imsDB
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ec1aa3041f3e561219a3229e82d1da1482ab5b109c1c16e4b84eb8207843cfaff1f3465962650945c45bab2c9ecdd0ca06e4d6567556b2c89048fa9eea42793f
jwt.expirationMs=600000
jwt.refreshExpirationMs=900000

 
 
 